#!/usr/bin/env bash
set -euo pipefail

# Install this repo's agent config into Claude Code, and its extension list
# into VS Code.
#
#   ./install.sh                    install into every tool detected on this machine
#   ./install.sh claude             install into one tool
#   ./install.sh claude vscode      install into several
#   ./install.sh vscode             install the VS Code extensions that are missing
#   ./install.sh skills             link only the skills
#   ./install.sh all                install into all tools, detected or not
#   ./install.sh --dry-run all      print the plan, change nothing
#
# Layout:
#   core/          source of truth: agents and skills
#   adapters/claude/  CLAUDE.md + settings.json + keybindings.json
#   adapters/vscode/  extensions.txt
#   scripts/       skill lint, packaging for claude.ai, claude.ai drift check
#   build/         generated by package-skills.sh, gitignored

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_ROOT="$HOME/.agent-config-backups/$(date +%Y%m%d-%H%M%S)"

DRY_RUN=0
TOOLS=()

# ---------------------------------------------------------------- output ----

if [ -t 1 ]; then
    B=$'\033[1m'; DIM=$'\033[2m'; YEL=$'\033[33m'; RED=$'\033[31m'; RST=$'\033[0m'
else
    B=""; DIM=""; YEL=""; RED=""; RST=""
fi

step() { printf '\n%s==> %s%s\n' "$B" "$1" "$RST"; }
say()  { printf '    %s\n' "$1"; }
note() { printf '    %s%s%s\n' "$DIM" "$1" "$RST"; }
warn() { printf '    %s! %s%s\n' "$YEL" "$1" "$RST" >&2; }
die()  { printf '%serror: %s%s\n' "$RED" "$1" "$RST" >&2; exit 1; }

usage() { awk 'NR == 1 { next } /^#/ { seen = 1; sub(/^# ?/, ""); print; next } seen { exit }' "${BASH_SOURCE[0]}"; exit 0; }

# ------------------------------------------------------------ primitives ----

# Every filesystem mutation goes through these so --dry-run is airtight.

mk() {  # mk <dir>
    [ "$DRY_RUN" = 1 ] || mkdir -p "$1"
}

# Bookkeeping for link(). GONE: paths backup() and drop() cleared this run, one
# "<path><TAB><old link target>" per line, so link() can still say what was
# there; under --dry-run nothing is cleared, and this is how link() knows a real
# file would have been backed up. LINKED: every dst link() made, or under
# --dry-run would make, one per line.
GONE=""
LINKED=""
gone() { GONE+="$1"$'\t'"$2"$'\n'; }  # gone <path> <old target, empty if not a link>
was_gone() {  # was_gone <path> — print its old target; fail if it was not cleared
    printf '%s' "$GONE" | awk -F'\t' -v p="$1" '$1 == p { t = $2; hit = 1 } END { if (!hit) exit 1; print t }'
}

# link <src> <dst> — says new, exists (already this link) or replace. Refuses a
# real file or directory at dst: ln -sfn would overwrite the file, or nest the
# link inside the directory while the directory stays in use.
link() {
    local src="$1" dst="$2" old state
    if [ -L "$dst" ]; then
        old=$(readlink "$dst")
        if [ "$old" = "$src" ]; then state=exists; else state=replace; fi
    elif old=$(was_gone "$dst"); then
        if [ "$old" = "$src" ]; then state=exists; else state=replace; fi
    elif [ -e "$dst" ]; then
        if [ -d "$dst" ]; then old="directory"; else old="file"; fi
        warn "$dst is a real $old, not a link; left alone. Move it away and re-run to link ${src#"$REPO_DIR"/}."
        return 0
    else
        state=new
    fi
    say "link $(printf '%-7s' "$state") $dst -> ${src#"$REPO_DIR"/}"
    LINKED+="$dst"$'\n'
    [ "$DRY_RUN" = 1 ] || { mkdir -p "$(dirname "$dst")"; ln -sfn "$src" "$dst"; }
}

copy() {  # copy <src> <dst>
    say "copy $2"
    [ "$DRY_RUN" = 1 ] || { mkdir -p "$(dirname "$2")"; cp "$1" "$2"; }
}

# drop <path> — remove one of our own symlinks; link() recreates it.
drop() {
    gone "$1" "$(readlink "$1")"
    [ "$DRY_RUN" = 1 ] || rm "$1"
}

# backup <path> <label> — move an existing real file/dir out of the way.
# Symlinks into this repo are ours; drop them silently, they get recreated.
backup() {
    local path="$1" label="$2"
    [ -e "$path" ] || [ -L "$path" ] || return 0
    if [ -L "$path" ]; then
        case "$(readlink "$path")" in
            "$REPO_DIR"/*) drop "$path"; return 0 ;;
        esac
    fi
    say "backup $path -> $BACKUP_ROOT/$label/"
    gone "$path" ""
    [ "$DRY_RUN" = 1 ] || {
        mkdir -p "$BACKUP_ROOT/$label"
        mv "$path" "$BACKUP_ROOT/$label/$(basename "$path")"
    }
}

# sweep_dir <dir> <label> [keep] — make dir mirror the repo exactly: everything
# not ours is backed up, except entries named in the space-separated keep list.
# ONLY for directories this repo owns outright.
sweep_dir() {
    local dir="$1" label="$2" keep=" ${3-} " entry
    [ -d "$dir" ] || return 0
    for entry in "$dir"/* "$dir"/.[!.]*; do
        [ -e "$entry" ] || [ -L "$entry" ] || continue
        case "$keep" in *" ${entry##*/} "*) continue ;; esac
        backup "$entry" "$label"
    done
}

# ---------------------------------------------------------------- skills ----

# The skills blocks, shared by install_claude and `./install.sh skills`.

link_skills() {  # link_skills <dir> — link every core/skills/<name> into dir
    local d
    for d in "$REPO_DIR"/core/skills/*/; do
        [ -d "$d" ] || continue
        link "${d%/}" "$1/$(basename "$d")"
    done
}

# ~/.claude/skills is swept. synced/ holds the claude.ai skills and .trash/ is
# where Claude Code parks them when syncing is turned off; both belong to
# Claude Code, not this repo.
skills_claude() {
    mk "$1"
    sweep_dir "$1" claude/skills "synced .trash"
    link_skills "$1"
}

# report_skills <dir>... — name every core skill a dir does not link to this
# repo. A dry run counts the links it planned above as made.
report_skills() {
    local dir d n missing other clean=1
    for dir in "$@"; do
        missing=""; other=""
        for d in "$REPO_DIR"/core/skills/*/; do
            [ -d "$d" ] || continue
            n=$(basename "$d")
            if [ -L "$dir/$n" ] && [ "$(readlink "$dir/$n")" = "${d%/}" ]; then
                continue
            elif [ "$DRY_RUN" = 1 ] && printf '%s' "$LINKED" | grep -Fxq -- "$dir/$n"; then
                continue
            elif [ -e "$dir/$n" ] || [ -L "$dir/$n" ]; then
                other+=" $n"
            else
                missing+=" $n"
            fi
        done
        [ -z "$missing" ] || { warn "missing from $dir:$missing"; clean=0; }
        [ -z "$other" ] || { warn "in $dir but not linked to this repo:$other"; clean=0; }
    done
    [ "$clean" = 0 ] || note "every core skill is linked from $*"
}

install_skills() {
    local c="$HOME/.claude/skills"
    step "Skills -> $c"
    skills_claude "$c"
    report_skills "$c"
}

# Lint core/skills and compare them with the claude.ai copies. Both only report:
# a skill that fails is still linked, because the linked copy is the one to fix.
skill_checks() {
    step "Skill checks"
    "$REPO_DIR/scripts/check-skills.sh" --quiet 2>&1 | sed 's/^/    /' ||
        warn "check-skills failed; run scripts/check-skills.sh for the full report"
    "$REPO_DIR/scripts/skill-sync-status.sh" --quiet 2>&1 | sed 's/^/    /' ||
        warn "the claude.ai copies differ; see \"Skills and claude.ai\" in README.md"
}

# ----------------------------------------------------------------- tools ----

install_claude() {
    local dir="$HOME/.claude"
    step "Claude Code -> $dir"
    mk "$dir"

    # statusline (submodule; Claude-only feature)
    backup "$dir/statusline" claude
    link "$REPO_DIR/statusline" "$dir/statusline"
    [ "$DRY_RUN" = 1 ] || chmod +x "$REPO_DIR/statusline/statusline.sh"

    # instructions
    backup "$dir/CLAUDE.md" claude
    link "$REPO_DIR/adapters/claude/CLAUDE.md" "$dir/CLAUDE.md"

    # agents — core format is Claude format, so these link straight through
    mk "$dir/agents"
    sweep_dir "$dir/agents" claude/agents
    local f
    for f in "$REPO_DIR"/core/agents/*.md; do
        [ -e "$f" ] || continue
        link "$f" "$dir/agents/$(basename "$f")"
    done

    # skills — swept, except Claude Code's own synced/ and .trash/
    skills_claude "$dir/skills"

    # settings and keybindings are copies: Claude rewrites settings.json in
    # place (theme, model picker), and a symlink would push that into the repo.
    backup "$dir/settings.json" claude
    copy "$REPO_DIR/adapters/claude/settings.json" "$dir/settings.json"
    backup "$dir/keybindings.json" claude
    copy "$REPO_DIR/adapters/claude/keybindings.json" "$dir/keybindings.json"
}

# --------------------------------------------------------------- vscode ----

# VS Code's CLI. `code` is only on PATH after "Shell Command: Install 'code'
# command in PATH" from the Command Palette; fall back to the macOS app bundle.
vscode_cli() {
    local c
    if c=$(command -v code 2>/dev/null); then printf '%s\n' "$c"; return 0; fi
    c="/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
    if [ -x "$c" ]; then printf '%s\n' "$c"; return 0; fi
    return 1
}

# Normalise an extension list (stdin) to one lowercase ID per line, sorted, so
# the lists can be diffed with comm. Marketplace IDs are case-insensitive and
# `--list-extensions` prints them lowercase. Strips comments and blank lines.
ext_ids() {
    awk '{ sub(/#.*/, ""); gsub(/[[:space:]]/, ""); if ($0 != "") print tolower($0) }' | sort -u
}

install_vscode() {
    local list="$REPO_DIR/adapters/vscode/extensions.txt" code
    step "VS Code extensions"
    [ -f "$list" ] || die "missing $list"
    code=$(vscode_cli) || {
        warn "VS Code CLI not found; skipping. Install VS Code, then run \"Shell Command: Install 'code' command in PATH\" from the Command Palette."
        return 0
    }
    note "using $code"

    local wanted have missing extra
    wanted=$(ext_ids < "$list")
    have=$("$code" --list-extensions 2>/dev/null | ext_ids)
    missing=$(comm -23 <(printf '%s\n' "$wanted") <(printf '%s\n' "$have"))
    extra=$(comm -13 <(printf '%s\n' "$wanted") <(printf '%s\n' "$have"))

    if [ -z "$missing" ]; then
        note "all $(printf '%s\n' "$wanted" | wc -l | tr -d ' ') extensions already installed"
    else
        local args=() id
        while IFS= read -r id; do
            say "install $id"
            args+=(--install-extension "$id")
        done <<< "$missing"
        if [ "$DRY_RUN" = 0 ]; then
            # One invocation: every `code` launch costs a second or two. A
            # marketplace failure must not abort the rest of the install; the
            # re-check below reports what did not land.
            "$code" "${args[@]}" 2>&1 | sed 's/^/      /' || true
            missing=$(comm -23 <(printf '%s\n' "$wanted") <("$code" --list-extensions 2>/dev/null | ext_ids))
            [ -z "$missing" ] || warn "not installed: $(printf '%s' "$missing" | tr '\n' ' ')"
        fi
    fi
    # Report, never remove: the list is what a fresh machine should get, not a
    # ban on installing anything else.
    [ -z "$extra" ] || note "installed here but not in extensions.txt: $(printf '%s' "$extra" | tr '\n' ' ')"
}

# ------------------------------------------------------------------ main ----

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help) usage ;;
        -n|--dry-run) DRY_RUN=1 ;;
        all) TOOLS=(claude vscode) ;;
        claude|vscode|skills) TOOLS+=("$1") ;;
        -*) die "unknown flag: $1 (try --help)" ;;
        *) die "unknown tool: $1 (expected claude, vscode, skills, or all)" ;;
    esac
    shift
done

if [ ${#TOOLS[@]} -eq 0 ]; then
    if command -v claude >/dev/null 2>&1 || [ -d "$HOME/.claude" ]; then TOOLS+=(claude); fi
    if vscode_cli >/dev/null 2>&1 || [ -d "$HOME/.vscode" ]; then TOOLS+=(vscode); fi
    [ ${#TOOLS[@]} -gt 0 ] || die "no supported tool detected; name one explicitly (claude|vscode|skills)"
    note "detected: ${TOOLS[*]}"
fi

# de-duplicate while preserving order
UNIQ=()
for t in "${TOOLS[@]}"; do
    case " ${UNIQ[*]-} " in *" $t "*) continue ;; esac
    UNIQ+=("$t")
done
TOOLS=("${UNIQ[@]}")

printf '%sInstalling from %s%s\n' "$B" "$REPO_DIR" "$RST"
[ "$DRY_RUN" = 1 ] && printf '%s(dry run — nothing will be written)%s\n' "$YEL" "$RST"

# The only submodule is the Claude statusline.
case " ${TOOLS[*]} " in
    *" claude "*)
        if [ -f "$REPO_DIR/.gitmodules" ] && [ "$DRY_RUN" = 0 ]; then
            git -C "$REPO_DIR" submodule update --init --recursive
        fi ;;
esac

for t in "${TOOLS[@]}"; do
    "install_$t"
done

case " ${TOOLS[*]} " in
    *" claude "*|*" skills "*) skill_checks ;;
esac

printf '\n%sDone.%s Restart the tools you installed into.\n' "$B" "$RST"
[ -d "$BACKUP_ROOT" ] && say "backups: $BACKUP_ROOT"
exit 0
